name: shared_todo_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  url_launcher: ^6.2.0
  go_router: ^16.3.0
  intl: ^0.20.2

#Visualizzazione ad albero (TodoList - Folder - Task)
  animated_tree_view: ^2.3.0
  stomp_dart_client: ^3.0.1
  http: ^1.6.0

#librerie per la gestione della mappa !
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
#Alternativa:
  flutter_map: ^8.2.2           
  latlong2: ^0.9.1
# per salvare i dati e ottenerli facilmente ( gestione del theme persistente )
shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.3
  mocktail: ^1.0.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    # Dichiara l'intera cartella. Assicurati che l'indentazione
    # (i 2 spazi) sia corretta e che ci sia lo / finale.
    - assets/images/login_image.png