name: Flutter CI

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Print working directory (debug)
        run: pwd && ls -la

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./shared_todo_app

      - name: Check formatting
        run: flutter format --set-exit-if-changed .
        working-directory: ./shared_todo_app

      - name: Analyze code
        run: flutter analyze
        working-directory: ./shared_todo_app

      - name: Run tests
        # Questo comando esegue i test
        run: flutter test
        working-directory: ./shared_todo_app

      - name: Build APK (Debug)
        run: flutter build apk --debug
        working-directory: ./shared_todo_app